# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gakurobo.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1886, 987)
        MainWindow.setWindowTitle("robohan-GUI")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("robohan_icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.emergency = QtWidgets.QPushButton(self.centralwidget)
        self.emergency.setGeometry(QtCore.QRect(1650, 530, 171, 451))
        font = QtGui.QFont()
        font.setFamily("RaghuMalayalamSans")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.emergency.setFont(font)
        self.emergency.setObjectName("emergency")
        self.label_image1 = QtWidgets.QLabel(self.centralwidget)
        self.label_image1.setGeometry(QtCore.QRect(40, 390, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_image1.setFont(font)
        self.label_image1.setObjectName("label_image1")
        self.setpower = QtWidgets.QLabel(self.centralwidget)
        self.setpower.setGeometry(QtCore.QRect(10, 70, 341, 201))
        self.setpower.setText("")
        self.setpower.setPixmap(QtGui.QPixmap("setpower.jpg"))
        self.setpower.setScaledContents(True)
        self.setpower.setObjectName("setpower")
        self.setpower_w1 = QtWidgets.QLabel(self.centralwidget)
        self.setpower_w1.setGeometry(QtCore.QRect(260, 140, 67, 17))
        self.setpower_w1.setObjectName("setpower_w1")
        self.setpower_w4 = QtWidgets.QLabel(self.centralwidget)
        self.setpower_w4.setGeometry(QtCore.QRect(260, 230, 67, 17))
        self.setpower_w4.setObjectName("setpower_w4")
        self.setpower_w2 = QtWidgets.QLabel(self.centralwidget)
        self.setpower_w2.setGeometry(QtCore.QRect(30, 140, 67, 17))
        self.setpower_w2.setObjectName("setpower_w2")
        self.setpower_w3 = QtWidgets.QLabel(self.centralwidget)
        self.setpower_w3.setGeometry(QtCore.QRect(30, 230, 67, 17))
        self.setpower_w3.setObjectName("setpower_w3")
        self.condition = QtWidgets.QLabel(self.centralwidget)
        self.condition.setGeometry(QtCore.QRect(10, 20, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.condition.setFont(font)
        self.condition.setStyleSheet("background-color: rgb(96, 255, 112);\n"
"")
        self.condition.setTextFormat(QtCore.Qt.AutoText)
        self.condition.setScaledContents(True)
        self.condition.setWordWrap(True)
        self.condition.setObjectName("condition")
        self.image1 = QtWidgets.QLabel(self.centralwidget)
        self.image1.setGeometry(QtCore.QRect(30, 440, 821, 461))
        self.image1.setText("")
        self.image1.setPixmap(QtGui.QPixmap("robohan_title.jpg"))
        self.image1.setScaledContents(True)
        self.image1.setObjectName("image1")
        self.map = QtWidgets.QGraphicsView(self.centralwidget)
        self.map.setGeometry(QtCore.QRect(900, 90, 741, 881))
        self.map.setSceneRect(QtCore.QRectF(0.0, 0.0, 411.67, 806.67))
        self.map.setObjectName("map")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(900, 10, 731, 71))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.timer = QtWidgets.QLabel(self.layoutWidget)
        self.timer.setTextFormat(QtCore.Qt.AutoText)
        self.timer.setScaledContents(False)
        self.timer.setObjectName("timer")
        self.horizontalLayout.addWidget(self.timer)
        self.timer_button = QtWidgets.QPushButton(self.layoutWidget)
        self.timer_button.setObjectName("timer_button")
        self.horizontalLayout.addWidget(self.timer_button)
        self.timebar = QtWidgets.QProgressBar(self.splitter)
        self.timebar.setProperty("value", 100)
        self.timebar.setObjectName("timebar")
        self.change_stage = QtWidgets.QPushButton(self.centralwidget)
        self.change_stage.setGeometry(QtCore.QRect(1650, 260, 171, 261))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.change_stage.setFont(font)
        self.change_stage.setStyleSheet("background-color: rgb(52, 101, 164);")
        self.change_stage.setObjectName("change_stage")
        self.rogo = QtWidgets.QLabel(self.centralwidget)
        self.rogo.setGeometry(QtCore.QRect(1640, 10, 191, 71))
        self.rogo.setText("")
        self.rogo.setPixmap(QtGui.QPixmap("robohan_title.jpg"))
        self.rogo.setScaledContents(True)
        self.rogo.setObjectName("rogo")
        self.move_check = QtWidgets.QPushButton(self.centralwidget)
        self.move_check.setGeometry(QtCore.QRect(1650, 100, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.move_check.setFont(font)
        self.move_check.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.move_check.setObjectName("move_check")
        self.clear_path = QtWidgets.QPushButton(self.centralwidget)
        self.clear_path.setGeometry(QtCore.QRect(1650, 180, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.clear_path.setFont(font)
        self.clear_path.setStyleSheet("background-color: rgb(245, 121, 0);")
        self.clear_path.setObjectName("clear_path")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(566, 120, 102, 314))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sairo_3_up = QtWidgets.QLabel(self.layoutWidget_2)
        self.sairo_3_up.setMaximumSize(QtCore.QSize(100, 100))
        self.sairo_3_up.setText("")
        self.sairo_3_up.setPixmap(QtGui.QPixmap("../../Downloads/nothing.jpg"))
        self.sairo_3_up.setScaledContents(True)
        self.sairo_3_up.setObjectName("sairo_3_up")
        self.verticalLayout_2.addWidget(self.sairo_3_up)
        self.sairo_3_cen = QtWidgets.QLabel(self.layoutWidget_2)
        self.sairo_3_cen.setMaximumSize(QtCore.QSize(100, 100))
        self.sairo_3_cen.setText("")
        self.sairo_3_cen.setPixmap(QtGui.QPixmap("../../Downloads/nothing.jpg"))
        self.sairo_3_cen.setScaledContents(True)
        self.sairo_3_cen.setObjectName("sairo_3_cen")
        self.verticalLayout_2.addWidget(self.sairo_3_cen)
        self.sairo_3_down = QtWidgets.QLabel(self.layoutWidget_2)
        self.sairo_3_down.setMaximumSize(QtCore.QSize(100, 100))
        self.sairo_3_down.setText("")
        self.sairo_3_down.setPixmap(QtGui.QPixmap("../../Downloads/nothing.jpg"))
        self.sairo_3_down.setScaledContents(True)
        self.sairo_3_down.setObjectName("sairo_3_down")
        self.verticalLayout_2.addWidget(self.sairo_3_down)
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(674, 120, 102, 314))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sairo_4_up = QtWidgets.QLabel(self.layoutWidget_3)
        self.sairo_4_up.setMaximumSize(QtCore.QSize(100, 100))
        self.sairo_4_up.setText("")
        self.sairo_4_up.setPixmap(QtGui.QPixmap("../../Downloads/nothing.jpg"))
        self.sairo_4_up.setScaledContents(True)
        self.sairo_4_up.setObjectName("sairo_4_up")
        self.verticalLayout_3.addWidget(self.sairo_4_up)
        self.sairo_4_cen = QtWidgets.QLabel(self.layoutWidget_3)
        self.sairo_4_cen.setMaximumSize(QtCore.QSize(100, 100))
        self.sairo_4_cen.setText("")
        self.sairo_4_cen.setPixmap(QtGui.QPixmap("../../Downloads/nothing.jpg"))
        self.sairo_4_cen.setScaledContents(True)
        self.sairo_4_cen.setObjectName("sairo_4_cen")
        self.verticalLayout_3.addWidget(self.sairo_4_cen)
        self.sairo_4_down = QtWidgets.QLabel(self.layoutWidget_3)
        self.sairo_4_down.setMaximumSize(QtCore.QSize(100, 100))
        self.sairo_4_down.setText("")
        self.sairo_4_down.setPixmap(QtGui.QPixmap("../../Downloads/nothing.jpg"))
        self.sairo_4_down.setScaledContents(True)
        self.sairo_4_down.setObjectName("sairo_4_down")
        self.verticalLayout_3.addWidget(self.sairo_4_down)
        self.layoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_5.setGeometry(QtCore.QRect(782, 120, 102, 314))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.sairo_5_up = QtWidgets.QLabel(self.layoutWidget_5)
        self.sairo_5_up.setMaximumSize(QtCore.QSize(100, 100))
        self.sairo_5_up.setText("")
        self.sairo_5_up.setPixmap(QtGui.QPixmap("../../Downloads/nothing.jpg"))
        self.sairo_5_up.setScaledContents(True)
        self.sairo_5_up.setObjectName("sairo_5_up")
        self.verticalLayout_5.addWidget(self.sairo_5_up)
        self.sairo_5_cen = QtWidgets.QLabel(self.layoutWidget_5)
        self.sairo_5_cen.setMaximumSize(QtCore.QSize(100, 100))
        self.sairo_5_cen.setText("")
        self.sairo_5_cen.setPixmap(QtGui.QPixmap("../../Downloads/nothing.jpg"))
        self.sairo_5_cen.setScaledContents(True)
        self.sairo_5_cen.setObjectName("sairo_5_cen")
        self.verticalLayout_5.addWidget(self.sairo_5_cen)
        self.sairo_5_down = QtWidgets.QLabel(self.layoutWidget_5)
        self.sairo_5_down.setMaximumSize(QtCore.QSize(100, 100))
        self.sairo_5_down.setText("")
        self.sairo_5_down.setPixmap(QtGui.QPixmap("../../Downloads/nothing.jpg"))
        self.sairo_5_down.setScaledContents(True)
        self.sairo_5_down.setObjectName("sairo_5_down")
        self.verticalLayout_5.addWidget(self.sairo_5_down)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(359, 69, 521, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sairo_label_1 = QtWidgets.QLabel(self.layoutWidget1)
        self.sairo_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.sairo_label_1.setObjectName("sairo_label_1")
        self.horizontalLayout_2.addWidget(self.sairo_label_1)
        self.sairo_label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.sairo_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.sairo_label_2.setObjectName("sairo_label_2")
        self.horizontalLayout_2.addWidget(self.sairo_label_2)
        self.sairo_label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.sairo_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.sairo_label_3.setObjectName("sairo_label_3")
        self.horizontalLayout_2.addWidget(self.sairo_label_3)
        self.sairo_label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.sairo_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.sairo_label_4.setObjectName("sairo_label_4")
        self.horizontalLayout_2.addWidget(self.sairo_label_4)
        self.sairo_label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.sairo_label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.sairo_label_5.setObjectName("sairo_label_5")
        self.horizontalLayout_2.addWidget(self.sairo_label_5)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(390, 0, 451, 65))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget2)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.kp_label = QtWidgets.QLabel(self.layoutWidget2)
        self.kp_label.setObjectName("kp_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.kp_label)
        self.kp = QtWidgets.QSlider(self.layoutWidget2)
        self.kp.setMaximum(100)
        self.kp.setPageStep(1)
        self.kp.setSliderPosition(30)
        self.kp.setOrientation(QtCore.Qt.Horizontal)
        self.kp.setObjectName("kp")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.kp)
        self.ki_label = QtWidgets.QLabel(self.layoutWidget2)
        self.ki_label.setObjectName("ki_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ki_label)
        self.ki = QtWidgets.QSlider(self.layoutWidget2)
        self.ki.setMaximum(100)
        self.ki.setPageStep(1)
        self.ki.setSliderPosition(2)
        self.ki.setOrientation(QtCore.Qt.Horizontal)
        self.ki.setObjectName("ki")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ki)
        self.kd_label = QtWidgets.QLabel(self.layoutWidget2)
        self.kd_label.setObjectName("kd_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.kd_label)
        self.kd = QtWidgets.QSlider(self.layoutWidget2)
        self.kd.setMaximum(100)
        self.kd.setPageStep(1)
        self.kd.setSliderPosition(1)
        self.kd.setOrientation(QtCore.Qt.Horizontal)
        self.kd.setObjectName("kd")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.kd)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(350, 120, 102, 314))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sairo_1_up = QtWidgets.QLabel(self.layoutWidget3)
        self.sairo_1_up.setMaximumSize(QtCore.QSize(100, 100))
        self.sairo_1_up.setText("")
        self.sairo_1_up.setPixmap(QtGui.QPixmap("../../Downloads/nothing.jpg"))
        self.sairo_1_up.setScaledContents(True)
        self.sairo_1_up.setAlignment(QtCore.Qt.AlignCenter)
        self.sairo_1_up.setObjectName("sairo_1_up")
        self.verticalLayout.addWidget(self.sairo_1_up)
        self.sairo_1_cen = QtWidgets.QLabel(self.layoutWidget3)
        self.sairo_1_cen.setMaximumSize(QtCore.QSize(100, 100))
        self.sairo_1_cen.setText("")
        self.sairo_1_cen.setPixmap(QtGui.QPixmap("../../Downloads/nothing.jpg"))
        self.sairo_1_cen.setScaledContents(True)
        self.sairo_1_cen.setObjectName("sairo_1_cen")
        self.verticalLayout.addWidget(self.sairo_1_cen)
        self.sairo_1_down = QtWidgets.QLabel(self.layoutWidget3)
        self.sairo_1_down.setMaximumSize(QtCore.QSize(100, 100))
        self.sairo_1_down.setText("")
        self.sairo_1_down.setPixmap(QtGui.QPixmap("../../Downloads/nothing.jpg"))
        self.sairo_1_down.setScaledContents(True)
        self.sairo_1_down.setObjectName("sairo_1_down")
        self.verticalLayout.addWidget(self.sairo_1_down)
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(458, 120, 102, 314))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.sairo_2_up = QtWidgets.QLabel(self.layoutWidget4)
        self.sairo_2_up.setMaximumSize(QtCore.QSize(100, 100))
        self.sairo_2_up.setText("")
        self.sairo_2_up.setPixmap(QtGui.QPixmap("../../Downloads/nothing.jpg"))
        self.sairo_2_up.setScaledContents(True)
        self.sairo_2_up.setObjectName("sairo_2_up")
        self.verticalLayout_4.addWidget(self.sairo_2_up)
        self.sairo_2_cen = QtWidgets.QLabel(self.layoutWidget4)
        self.sairo_2_cen.setMaximumSize(QtCore.QSize(100, 100))
        self.sairo_2_cen.setText("")
        self.sairo_2_cen.setPixmap(QtGui.QPixmap("../../Downloads/nothing.jpg"))
        self.sairo_2_cen.setScaledContents(True)
        self.sairo_2_cen.setObjectName("sairo_2_cen")
        self.verticalLayout_4.addWidget(self.sairo_2_cen)
        self.sairo_2_down = QtWidgets.QLabel(self.layoutWidget4)
        self.sairo_2_down.setMaximumSize(QtCore.QSize(100, 100))
        self.sairo_2_down.setText("")
        self.sairo_2_down.setPixmap(QtGui.QPixmap("../../Downloads/nothing.jpg"))
        self.sairo_2_down.setScaledContents(True)
        self.sairo_2_down.setObjectName("sairo_2_down")
        self.verticalLayout_4.addWidget(self.sairo_2_down)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.splitter.raise_()
        self.layoutWidget.raise_()
        self.image1.raise_()
        self.setpower.raise_()
        self.emergency.raise_()
        self.label_image1.raise_()
        self.setpower_w1.raise_()
        self.setpower_w4.raise_()
        self.setpower_w2.raise_()
        self.setpower_w3.raise_()
        self.condition.raise_()
        self.map.raise_()
        self.change_stage.raise_()
        self.rogo.raise_()
        self.move_check.raise_()
        self.clear_path.raise_()
        self.layoutWidget_2.raise_()
        self.layoutWidget_3.raise_()
        self.layoutWidget_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1886, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.emergency.setText(_translate("MainWindow", "Emergency"))
        self.label_image1.setText(_translate("MainWindow", "image1"))
        self.setpower_w1.setText(_translate("MainWindow", "set_w1"))
        self.setpower_w4.setText(_translate("MainWindow", "set_w4"))
        self.setpower_w2.setText(_translate("MainWindow", "set_w2"))
        self.setpower_w3.setText(_translate("MainWindow", "set_w3"))
        self.condition.setText(_translate("MainWindow", "現在の状態"))
        self.timer.setText(_translate("MainWindow", "残り時間： 3:00"))
        self.timer_button.setText(_translate("MainWindow", "タイマー開始"))
        self.change_stage.setText(_translate("MainWindow", "ChangeStage"))
        self.move_check.setText(_translate("MainWindow", "MoveCheck"))
        self.clear_path.setText(_translate("MainWindow", "ClearPath"))
        self.sairo_label_1.setText(_translate("MainWindow", "サイロ１"))
        self.sairo_label_2.setText(_translate("MainWindow", "サイロ２"))
        self.sairo_label_3.setText(_translate("MainWindow", "サイロ３"))
        self.sairo_label_4.setText(_translate("MainWindow", "サイロ４"))
        self.sairo_label_5.setText(_translate("MainWindow", "サイロ５"))
        self.kp_label.setText(_translate("MainWindow", "Kp : 0.30"))
        self.ki_label.setText(_translate("MainWindow", "Ki : 0.02"))
        self.kd_label.setText(_translate("MainWindow", "Kd : 0.01"))
